name: Build and publish to docs (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      - name: Build (hash router + base path)
        env:
          VITE_BASE: /guest-suite/
          VITE_ROUTER: hash
        run: npm run build

      - name: Publish to docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -R dist/* docs/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "No changes in docs. Skipping commit."
          else
            git commit -m "Deploy site to docs [skip ci]"
            git push
          fi

